### ISSUE TITLE
:X behaves differently when we drag on the screen than when we define via input language

### ISSUE THREAD

**Issue by brunorohde** [LGoodacre/context-sequencer#1]
Hi, i'm Bruno from Brasil.
Congratulations on the excellent work. I just started studying and testing it.
I found what appears to be a bug in the :X parameter definition. For example, setting :X as 16 via message (or creation argument) gives us 16 toggles, including the last one. If we define :X by dragging on the screen, with :X 16 we get 17 toggles, 16 steps plus the last toggle. I think it's missing to include the last toggle when we set :X via message. It seems that the correct operation is what we get dragging on the screen, since the last toggle is not included as a musical division of the unit, as the manual says. I'm including a video (as a .zip file) to illustrate the problem.
Thank you for your time and effort.
[context_bug_X.zip](https://github.com/LGoodacre/context-sequencer/files/1901085/context_bug_X.zip)

**Comment by LGoodacre** [comment]
Hi Bruno. Sorry for not seeing this earlier--I haven't been checking the issues page!
What you're seeing is not a "bug" but a "feature" (probably a very bad one). I changed the :X label on dragging to be -1 of the real :X value in response to feedback from another user. The feedback was as follows: it's quite counter-intuitive to scroll to 9 if you want 8 beats in the bar!

You're right that the best solution would be to change how the language so that ":X 4" gives a length of 5, including the last toggle. However, it's too late for such a change, as it would corrupt every patch that's already saved.

Maybe the second best solution would be to modify the label so that it says something like "4 boxes (:X 5)". What do you think?

**Comment by brunorohde** [comment]
Hi Liam, I opened an issue here because you indicated to do this in the workshop posted on video if I'm not mistaken. I've even found other bugs that I'll eventually list here too, or by any other means you indicate.

I think the :X parameter should maintain a consistent pattern between the definition via messages (and argument creation) or by dragging on the screen. Having two different units for the same parameter seems more counter-intuitive than setting a sequence of 8 steps plus the last toggle as value 9, which I consider simple and clear. Considering the compatibility argument, perhaps the solution to change the tag when dragging on the screen helps and lessen the confusion, keeping the X value always as number of steps plus 1 (last toggle), the way the argument is saved in the instance. As a suggestion, the tag could be: "8 steps (:X 9)"

**Comment by LGoodacre** [comment]
Yes, please do post bugs here! I haven't been checking because nobody's been posting, but I definitely want feedback, and this is the right place. You can also join the Facebook group if you like, which is a little more active: https://www.facebook.com/groups/123031095094961/.

"8 steps (:X 9)" is definitely doable; it's just a matter of which option is least confusing for the user. I might ask on the FB group to see what other people think...

**Comment by LGoodacre** [comment]
The latest commit implements the ":X 9 (8 steps)" idea, so I'm marking this as closed. But please let me know if you think it still needs further improvement. 

What other bugs have you spotted?
