### ISSUE TITLE
Context 5.0 in Deken

### ISSUE THREAD

**Issue by th555** [LGoodacre/context-sequencer#3]
Hello,
Context looks great! Would it be possible to get v5.0 in Deken as well?

**Comment by LGoodacre** [comment]
Hello, thanks for your interest in Context! Unfortunately there isn't much hope for updating Context at this point. The software is highly dependent on external libraries and GUI hacks, which makes it very difficult to maintain. Some of the external libraries have breaking changes which affect Context, and I suspect that recent versions of PD do as well. If you want to run Context, your best bet is to use PD 0.49, and use the externals that come with the download package.

If Context were to be updated, I think that the best way of doing it would be to take all of the external libraries and compile them into one package which can be redistributed. This is a lot of work, and unfortunately I don't have time for it any more. But if anyone is willing to help, I'd be willing to work together on it.

This PD library is more or less abandoned, but not because I've given up on the idea. I'm now working on implementing a new generative sequencer as a standalone application and as a VST3 plugin, which will hopefully be much more reliable when it's finished. If you want updates on this, you can join the Facebook group. I should have a working prototype and a demo video ready within a few months.

**Comment by th555** [comment]
Ok, thanks for the comment! I'll stick with 0.4 from Deken then.
